// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmupmxethmafxeivfyxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtdXBteGV0aG1hZnhlaXZmeXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA3MzksImV4cCI6MjA2NTQ5NjczOX0.hLsZQ6y527bhzml6hMEarDTSC1BbAtm28LtV6C3sfCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);